// Source: original site's Terms of use. The appointment-form paragraph is new and should be reviewed by the doctor.
import type { Localized } from "./site";

export const terms: Localized<string[]> = {
  "el": [
    "Η αποδοχή των παρόντων όρων χρήσης λογίζεται ως γενομένη με την είσοδο και πλοήγηση του επισκέπτη στην ιστοσελίδα ioannisandromidas.gr. Η αποδοχή αυτή συνίσταται στη ρητή και ανεπιφύλακτη συμφωνία του με τους όρους αυτούς. Σε περίπτωση διαφωνίας του επισκέπτη με κάποιον από τους όρους, αυτός οφείλει να διακόψει την περιήγησή του/της σε αυτήν.",
    "Η ιστοσελίδα ioannisandromidas.gr έχει υλοποιηθεί αποκλειστικά για την παροχή πληροφοριών στους επισκέπτες σχετικά με το ιατρείο του Ιωάννη Ν. Ανδρομιδά και δεν απαιτεί και δεν συλλέγει δεδομένα προσωπικού χαρακτήρα από τους επισκέπτες του. Το περιεχόμενο του ιστολογίου αποτελεί πνευματική ιδιοκτησία του ioannisandromidas.gr (εκτός αν το θέμα έχει παρθεί από άλλη ιστοσελίδα οπότε ανήκει στη πηγή του) αποτελεί αντικείμενο αποκλειστικών δικαιωμάτων πνευματικής και βιομηχανικής ιδιοκτησίας των νόμιμων δικαιούχων τους και προστατεύεται από τις σχετικές διατάξεις περί πνευματικής ιδιοκτησίας του ελληνικού και ευρωπαϊκού δικαίου και των διεθνών συμβάσεων. Συνεπώς, απαγορεύεται ρητά η αναδημοσίευση, η χρήση υλικού από τα περιεχόμενα της παρούσας ιστοσελίδας, όπως επίσης και η αντιγραφή, διανομή, αναμετάδοση οποιασδήποτε πληροφορίας βρίσκεται στην ιστοσελίδα αυτή, χωρίς την πρότερη έγγραφη έγκριση. Τονίζεται δε ότι απαγορεύεται αυστηρά η χρήση από τρίτους των λογότυπων, εμπορικών σημάτων, εικαστικών δημιουργικών και διακριτικών γνωρισμάτων που περιλαμβάνονται στην ιστοσελίδα.",
    "Μέσω της φόρμας αιτήματος ραντεβού ο επισκέπτης μπορεί προαιρετικά να αποστείλει στοιχεία επικοινωνίας (ονοματεπώνυμο, τηλέφωνο, email) και σύντομη περιγραφή του προβλήματος. Τα στοιχεία αυτά χρησιμοποιούνται αποκλειστικά για την επικοινωνία με τον ασθενή και τον προγραμματισμό του ραντεβού, δεν κοινοποιούνται σε τρίτους και ο επισκέπτης μπορεί να ζητήσει τη διαγραφή τους στο ioannisandromidas@gmail.com.",
    "Το  ioannisandromidas.gr περιλαμβάνει links προς άλλα ανεξάρτητα websites τα οποία δεν ελέγχει, και σε καμία περίπτωση δεν ευθύνεται για τον τρόπο λειτουργίας τους ή την τήρηση των όρων Προστασίας των Προσωπικών Δεδομένων από αυτούς τους φορείς. Προβλήματα που τυχόν προκύψουν κατά την επίσκεψη/χρήση των δικτυακών τόπων στους οποίους παραπέμπουμε ανάγονται αποκλειστικά και μόνο στη σφαίρα ευθύνης των αντίστοιχων δικτυακών τόπων. Η παραπομπή σε άλλους δικτυακούς τόπους γίνεται προς διευκόλυνση των χρηστών μας και σε καμία περίπτωση δεν δημιουργεί οποιαδήποτε μορφής δέσμευση για οποιονδήποτε.",
    "Τέλος, παρότι έχει ληφθεί κάθε μέριμνα για την ακρίβεια του περιεχομένου της παρούσας ιστοσελίδας, το  ioannisandromidas.gr δεν φέρει καμία ευθύνη, άμεση ή έμμεση, για προβλήματα που ενδέχεται να προκύψουν από την ανάγνωση των περιεχομένων της ιστοσελίδας αυτής ή την παρερμηνεία των αναγραφόμενων σε αυτή. Επίσης το ioannisandromidas.gr  δεν ευθύνεται για τυχόν ζημιές που υποστεί ο επισκέπτης της ιστοσελίδας από την πλοήγησή του σε αυτή ή από την αδυναμία χρήσης αυτής, τις διακοπές ή τις καθυστερήσεις κατά τη χρήση της παρούσας ιστοσελίδας. Το περιεχόμενο της ιστοσελίδας  ioannisandromidas.gr έχει καθαρά ενημερωτικό χαρακτήρα και σε καμία περίπτωση δεν υποκαθιστά την κλινική εξέταση από τον γιατρό σας,τον οποίο πρέπει να συμβουλεύεστε για προσωπικά σας προβλήματα υγείας."
  ],
  "en": [
    "Acceptance of these terms of use is considered as starting with the entry and navigation of the visitor on the website ioannisandromidas.gr. Such acceptance consists of its express and unconditional agreement with those conditions. In case of disagreement of the visitor with any of the terms, he/she must interrupt his/her navigation of it.",
    "The website ioannisandromidas.gr has been implemented exclusively to provide information to visitors about the Doctor’s office of Ioannis N. Andromidas. The content of the website is the intellectual property of the ioannisandromidas.gr (unless the subject has been taken from another site in which case it belongs to its source) is the subject of exclusive intellectual and industrial property rights of their legal beneficiaries and is protected by the relevant copyright provisions of Greek and European law and international conventions. Therefore, it is expressly prohibited to republish, use material from the contents of this website, as well as copy, distribute, re-transmit any information found on this website, without prior written approval.",
    "Through the appointment request form a visitor may optionally submit contact details (name, phone, email) and a short description of the problem. These details are used solely to contact the patient and schedule the appointment, are not shared with third parties, and the visitor may request their deletion at ioannisandromidas@gmail.com.",
    "It is stressed that the use by third parties of the logos, trademarks, artistic creations and distinctive features included on the website is strictly prohibited. The ioannisandromidas.gr includes links to other independent websites which it does not control, and in no way is responsible for the way they operate or the observance of the terms of the Protection of Personal Data by these entities. Problems that may arise during the visit/use of the websites to which we refer relate solely to the sphere of responsibility of the respective websites. Referral to other websites is made to the convenience of our users and in no way creates any form of commitment for anyone.",
    "Finally, although all care has been taken for the accuracy of the content of this website, the ioannisandromidas.gr is not responsible, directly or indirectly, for problems that may arise from reading the contents of this website or misinterpreting those listed there in.",
    "Also, the ioannisandromidas.gr is not responsible for any damage suffered by the visitor of the website from its navigation to it or by the inability to use it, interruptions or delays in the use of this website. The content of the website ioannisandromidas.gr is purely informative and in no way replaces the clinical examination by your doctor, who should consult about all your personal health problems."
  ]
};
